### PR TITLE
Integration Test - Release - 2018/05/30 19:11:43

### PR DESCRIPTION
**Pull request by PRMergerTest1**
Auto create for integration test. AnotherAuthorUpdatedArticleFlow

### CODE REVIEW

**Comment by PRMerger13** [comment]
@PRMergerTest1 : Thanks for your contribution! The author, @v-caxian, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@PRMergerTest1 : Thanks for your contribution! The author, @v-caxian, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@PRMergerTest1 : Thanks for your contribution! The author, @v-caxian, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@PRMergerTest1 : Thanks for your contribution! The author, @v-caxian, has been notified to review your proposed change.

**Comment by PRMerger13** [comment]
@PRMergerTest1 : Thanks for your contribution! The author, @v-caxian, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@PRMergerTest1 : Thanks for your contribution! The author, @v-caxian, has been notified to review your proposed change.

**Pull request closed without merging**
