### PR TITLE
Create expressroute-howto-coexist-resource-manager.md

### PR DESCRIPTION
**Pull request by TinaLiuGirl**
test

### CODE REVIEW

**Comment by PRMerger19** [comment]
@TinaLiuGirl : Thanks for your contribution to the Azure documentation! The author, @charwen, has been notified to review your proposed change.

**Comment by PRMerger19** [comment]
@TinaLiuGirl : Thanks for your contribution to the Azure documentation! The author, @charwen, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@TinaLiuGirl : Thanks for your contribution to the Azure documentation! The author, @charwen, has been notified to review your proposed change.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@TinaLiuGirl: Only the author, @charwen, can sign off on this pull request.

**Pull request closed without merging**
