### PR TITLE
Rename README.md to README.mD

### PR DESCRIPTION
**Pull request by adunndevster**

### CODE REVIEW

**Comment by PRMerger16** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by PRMerger16** [comment]
@adunndevster : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Comment by adunndevster** [comment]
#sign-off

**Comment by PRMerger16** [comment]
It looks like you're trying to change the casing in a folder or file name. This isn’t allowed. Either revert to the original casing or completely change the file name to enable sign-off.

**Comment by adunndevster** [comment]
#sign-off

**Comment by PRMerger16** [comment]
@adunndevster: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger16** [comment]
@adunndevster : Thanks for your contribution! The author, @, has been notified to review your proposed change.

**Pull request closed without merging**
