### PR TITLE
Update test-file-03.md

### PR DESCRIPTION
**Pull request by TinaLiuGirl**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@msftgits : Thanks for your contribution! The author, @ v-caxian, has been notified to review your proposed change.

**Comment by TinaLiuGirl** [comment]
#please-close

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by v-caxian** [comment]
#sign-off

**Comment by TinaLiuGirl** [comment]
#hold-off

**Pull request closed without merging**
