### PR TITLE
Update demo.md

### PR DESCRIPTION
**Pull request by seshenoy**

### CODE REVIEW

**Comment by PRMerger15** [comment]
@seshenoy : Thanks for your contribution! The author, @ v-caxian, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@seshenoy : Thanks for your contribution! The author, @ v-caxian, has been notified to review your proposed change.

**Comment by seshenoy** [comment]
#sign-off

**Comment by PRMerger15** [comment]
@seshenoy: I'm sorry - only the author of this article, @v-caxian, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by seshenoy** [comment]
#hold-off

**Comment by seshenoy** [comment]
#please-close

**Pull request closed without merging**
