### PR TITLE
Update test-file-04.md

### PR DESCRIPTION
**Pull request by v-caxian**

### CODE REVIEW

**Comment by v-caxian** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@v-caxian: Only the author, @v-tinaliu, can sign off on this pull request.

**Comment by PRMerger12** [comment]
@v-caxian: Only the author, @v-tinaliu, can sign off on this pull request.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by PRMerger9** [comment]
@TinaLiuGirl: Only the author, @v-tinaliu, can sign off on this pull request.

**Pull request closed without merging**
