### PR TITLE
Brian patch 8

### PR DESCRIPTION
**Pull request by bharney**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@bharney : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger7** [comment]
@bharney : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bharney** [comment]
#sign-off

**Comment by PRMerger7** [comment]
@bharney: I'm sorry - only the author of this article, @bharney0, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger7** [comment]
@bharney: I'm sorry - only the author of this article, @bharney0, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by bharney0** [comment]
#sign-off

**Comment by lamebrain** [comment]
#hold-off and #sign-off but why?

**Comment by PRMerger19** [comment]
@lamebrain: I'm sorry - only the author of this article, @bharney0, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by lamebrain** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@lamebrain: I'm sorry - only the author of this article, @bharney0, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger19** [comment]
@lamebrain: I'm sorry - only the author of this article, @bharney0, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger19** [comment]
@lamebrain: I'm sorry - only the author of this article, @bharney0, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by lamebrain** [comment]
#hold-off and #sign-off but why?

**Comment by PRMerger19** [comment]
@lamebrain: I'm sorry - only the author of this article, @bharney0, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger20** [comment]
You can't sign off and hold off at the same time.

**Comment by lamebrain** [comment]
#hold-off and #sign-off but why?

**Comment by PRMerger20** [comment]
@lamebrain: I'm sorry - only the author of this article, @bharney0, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request closed without merging**
