### PR TITLE
Create expressroute-howto-coexist-resource-manager.md

### PR DESCRIPTION
**Pull request by TinaLiuGirl**
test

### CODE REVIEW

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@TinaLiuGirl : Thanks for your contribution! The author, @charwen, has been notified to review your proposed change.

**Comment by PRMerger9** [comment]
@v-caxian : Thanks for your contribution! The author, @charwen, has been notified to review your proposed change.

**Pull request closed without merging**
