### PR TITLE
Update test-file-03.md

### PR DESCRIPTION
**Pull request by TinaLiuGirl**

### CODE REVIEW

**Comment by PRMerger5** [comment]
@TinaLiuGirl : Thanks for your contribution to the Azure documentation! The author, @v-caxian, has been notified to review your proposed change.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by PRMerger3** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger5** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger-2** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger4** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger-2** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger3** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger3** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger-2** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger3** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Comment by PRMerger4** [comment]
@TinaLiuGirl: Only the author, @v-caxian, can sign off on this pull request.

**Pull request closed without merging**
