### PR TITLE
Create test-services-label

### PR DESCRIPTION
**Pull request by adunndevster**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by lamebrain** [comment]
#sign-off

**Comment by PRMerger17** [comment]
@lamebrain: I'm sorry - only the author of this article, @mlearned, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by mlearned** [comment]
@adunndevster  was this submitted by mistake? i don't recognize the files being changed here?

**Pull request closed without merging**
