### PR TITLE
Update non-micro.md

### PR DESCRIPTION
**Pull request by ramajw24**

### CODE REVIEW

**Comment by ramajw24** [comment]
#sign-off

**Comment by jamarw** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Comment by jamarw** [comment]
#sign-off

**Comment by PRMerger19** [comment]
@jamarw: I'm sorry - only the author of this article, @ramajw24, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by PRMerger19** [comment]
@jamarw: I'm sorry - only the author of this article, @ramajw24, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by ramajw24** [comment]
#sign-off

**Comment by PRMerger19** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Comment by PRMerger19** [comment]
Only Microsoft employees can sign off on PRs. Your PR will be routed for review.

**Pull request closed without merging**
