### PR TITLE
Update test-file-04.md

### PR DESCRIPTION
**Pull request by v-caxian**

### CODE REVIEW

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by v-caxian** [comment]
#sign-off

**Comment by PRMerger18** [comment]
@v-caxian: Only the author, @TinaLiuGirl, can sign off on this pull request.

**Comment by PRMerger9** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @TinaLiuGirl, has been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@v-caxian: Only the author, @TinaLiuGirl, can sign off on this pull request.

**Comment by PRMerger5** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @TinaLiuGirl, has been notified to review your proposed change.

**Pull request closed without merging**
