### PR TITLE
Update test-file-04.md

### PR DESCRIPTION
**Pull request by v-caxian**

### CODE REVIEW

**Comment by PRMerger12** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @TinaLiuGirl, has been notified to review your proposed change.

**Comment by v-caxian** [comment]
#sign-off

**Comment by PRMerger8** [comment]
@v-caxian: Only the author, @TinaLiuGirl, can sign off on this pull request.

**Comment by v-caxian** [comment]
#hold-off

**Comment by v-caxian** [comment]
#please-close

**Pull request closed without merging**
