### PR TITLE
Update test-file-04.md

### PR DESCRIPTION
**Pull request by v-caxian**

### CODE REVIEW

**Comment by PRMerger4** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @TinaLiuGirl, has been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @TinaLiuGirl, has been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @TinaLiuGirl, has been notified to review your proposed change.

**Comment by TinaLiuGirl** [comment]
#sign-off

**Comment by v-caxian** [comment]
#please-close

**Pull request closed without merging**
