### PR TITLE
Update demo.md

### PR DESCRIPTION
**Pull request by v-caxian**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@v-caxian : Thanks for your contribution! The author, @v-kaliu, has been notified to review your proposed change.

**Comment by v-caxian** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@v-caxian: I'm sorry - only the author of this article, @v-kaliu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by v-caxian** [comment]
#hold-off

**Comment by v-caxian** [comment]
#sign-off

**Comment by PRMerger6** [comment]
@v-caxian: I'm sorry - only the author of this article, @v-kaliu, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request closed without merging**
