### PR TITLE
Release brian3

### PR DESCRIPTION
**Pull request by bharney-msft**

### CODE REVIEW

**Comment by PRMerger19** [comment]
@bharney : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bharney-msft** [comment]
#assign bharney

**Comment by bharney-msft** [comment]
bharney is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by bharney-msft** [comment]
#assign bharney-msft

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
also is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
also adding another #assign adunndevster

**Comment by bharney-msft** [comment]
Assigning someone else for this one #reassign bharney-msft

**Comment by bharney-msft** [comment]
someone is not a valid GitHub ID, or is not a collaborator on this repo.

**Comment by bharney-msft** [comment]
Assigning someone else for this one #reassign bharney-msft

**Comment by bharney-msft** [comment]
Assigning someone else for this one #reassign bharney-msft

**Comment by bharney-msft** [comment]
Assigning someone else for this one #reassign bharney-msft

**Comment by bharney-msft** [comment]
Going to assign brian #assign bharney-msft see if he know anything about this?

**Comment by bharney-msft** [comment]
Going to reassign brian #reassign bharney-msft see if he know anything about this?

**Comment by bharney-msft** [comment]
`#assign <githubUsername>`  is how its used

**Comment by bharney-msft** [comment]
```
You can assign users like so: #assign username
```

**Comment by bharney-msft** [comment]
#assign adunndevster bharney-msft

**Comment by bharney-msft** [comment]
#reassign bharney-msft

**Comment by bharney-msft** [comment]
#assign bharney

**Comment by bharney-msft** [comment]
#assign bharney-msft

**Comment by bharney-msft** [comment]
#assign bharney-msft

**Comment by bharney-msft** [comment]
#sign-off

**Comment by PRMerger10** [comment]
@bharney-msft: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by bharney-msft** [comment]
@bharney-msft: I'm sorry - only the author of this article, @, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Comment by bharney-msft** [comment]
#assign bharney-msft

**Comment by PRMerger10** [comment]
@bharney : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by adunndevster** [comment]
#assign @adunndevster

**Comment by adunndevster** [comment]
#reassign bharney-msft

**Comment by adunndevster** [comment]
#reassign @lamebrain

**Pull request merged**
