### PR TITLE
Update test-file-04.md

### PR DESCRIPTION
**Pull request by v-caxian**

### CODE REVIEW

**Comment by PRMerger17** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @TinaLiuGirl, has been notified to review your proposed change.

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger3** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger3** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger5** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger4** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger4** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger-2** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Comment by PRMerger5** [comment]
## PRMerger Results
 | Criterion | Description |
 --- | --- | 
 File Change Percent | This PR contains file(s) with more than 20% file change.

**Pull request closed without merging**
