### PR TITLE
Release brian8

### PR DESCRIPTION
**Pull request by bharney**
Release brian8

### CODE REVIEW

**Comment by PRMerger15** [comment]
@bharney : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bharney-msft** [comment]
#reassign bharney-msft

**Comment by PRMerger17** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by bharney** [comment]
#sign-off

**Comment by bharney-msft** [comment]
@bharney: I'm sorry - only the author of this article, @adunndevster, can sign off on your changes. But we do have an exception process - if you are on the Microsoft content or product team for this product area, you can ask the PR review team to review and merge it by sending mail to the techdocprs alias.

**Pull request closed without merging**
