### PR TITLE
Update hardware-inventory-views-configuration-manager.md

### PR DESCRIPTION
**Pull request by adunndevster**

### CODE REVIEW

**Comment by PRMerger9** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger20** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger12** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Comment by PRMerger6** [comment]
@adunndevster : Thanks for your contribution! The author(s) have been notified to review your proposed change.

**Pull request closed without merging**
