### PR TITLE
Update test-file-03.md

### PR DESCRIPTION
**Pull request by v-caxian**

### CODE REVIEW

**Comment by PRMerger7** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @v-kaliu, has been notified to review your proposed change.

**Comment by PRMerger14** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @v-kaliu, has been notified to review your proposed change.

**Comment by PRMerger15** [comment]
@v-caxian : Thanks for your contribution to the Azure documentation! The author, @v-kaliu, has been notified to review your proposed change.

**Comment by v-qizho** [comment]
#sign-off

**Comment by PRMerger20** [comment]
@v-qizho: Only the author, @v-kaliu, can sign off on this pull request.

**Pull request closed without merging**
